# -*- coding: utf-8 -*-
"""Laboratorio1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/velugonzalez/Curso-python/blob/main/Laboratorio1.ipynb

**Ejercicio 1**
"""

def segs():
  try:
    Tiempo = int(input('Ingrese cantidad de segundos: '))
    Horas = int(Tiempo/60/60)
    print('Horas: {}'.format(Horas))
    Minutos = int(((Tiempo/60/60) - (Tiempo/60//60))*60)
    print('Minutos: {}'.format(Minutos))
    Segundos = int(round(float(((Tiempo/60) - (Tiempo//60))*60),0))
    print('Segundos: {}'.format(Segundos))
  except(ValueError):
    print('Dato invalido.')

segs()

"""**Ejercicio 2**"""

try:
  nota = int(input('Ingrese nota: '))
  aprueba = 71
  if(nota < 50):
    print('INSUFICIENTE -- diferencia para alcanzar nota aprobada: {} pts.'.format(aprueba-nota))
  elif(nota <= 60):
    print('REGULAR -- diferencia para alcanzar nota aprobada: {} pts.'.format(aprueba-nota))
  elif(nota <= 70):
    print('BIEN -- diferencia para alcanzar nota aprobada: {} pts.'.format(aprueba-nota))
  elif(nota <= 90):
    print('MUY BIEN')
  elif(nota <= 100):
    print('SOBRESALIENE')
  else:
    print("No se reconoce esa nota")
except(ValueError):
  print("Los datos no son validos.")

"""**Ejercicio 3**"""

try:
  n1 = int(input('Ingrese numero mayor: '))
  n2 = int(input('Ingrese numero menor: '))

  if (n1 <= n2): 
    print("El primer numero debe ser mayor al segundo")
  else:
    total = n1
    for i in range(n2, n1):
      total = total + i
    print(f"La suma es: {total}")
except (ValueError):
  print('Dato invalido.')

"""**Ejercicio 4**"""

def factores():
  numero = int(input("Escriba un numero mayor que cero: "))
  fac = []
  i = 1
  while (i <= numero):
   if numero % i == 0:
     fac.append (numero //i)
   i = i + 1
  for a in fac:
    print (a)

factores()

"""**Ejercicio 5**"""

from datetime import date

import datetime
hoy = date.today()
anhoAct = hoy.year
mesAct = hoy.month
diaAct = hoy.day

dia = int(input('Ingrese dia de nacimiento: '))
mes = int(input('Ingrese mes de nacimiento: '))
anio = int(input('Ingrese anio de nacimiento: '))

if(dia > diaAct):
  edadA = anhoAct - anio - 1
  edadM = (12 - mes) + mesAct -1
  edadD = (30 - dia) + diaAct
else:
  edadA = anhoAct - anio
  edadM = mesAct - mes
  edadD = diaAct - dia

if(mes >= mesAct):
  edadA = anhoAct - anio - 1
  edadM = (12 - mes) + mesAct -1
else:
  edadA = anhoAct - anio
  edadM = mesAct - mes

print(f'la edad es: {edadA} anios, {edadM} meses y {edadD} dias')

"""**Ejercico 6**"""

try:
  simbol = input('Inserte simbolo: ')
  x = int(input('Inserte cantidad de veces: '))

  if (x <= 0 ):
    raise ValueError('El numero debe ser entre 1 - 20')
  if (x >= 21):
    raise ValueError('El numero debe ser entre 1 - 20')
  if (len(simbol) == 0):
    raise ValueError('Debe ingresar un simbolo')
  if (len(simbol) > 1):
    raise ValueError('Solo debe ingresar un simbolo')
  
  espacio = ' ' * 5

  for i in range(1, x+1):
    fig1 = simbol * i
    fig2 = simbol * (x - i + 1)
    bloque1 = '{0:<{vx}}'. format(fig1, vx=x)
    bloque2 = '{0:>{vx}}'. format(fig2, vx=x)
    bloque3 = '{0:<{vx}}'. format(fig2, vx=x)
    bloque4 = '{0:>{vx}}'. format(fig1, vx=x)
    print(bloque1+espacio+bloque2+espacio+bloque3+espacio+bloque4)
except (ValueError) as err:
  print('Datos invalidos: ', str(err.args[0]))